//! Mermaid diagrams rendered as Unicode box art.
//!
//! Parsing produces a typed [`Diagram`](ast::Diagram); layout turns it into a
//! [`Canvas`](crate::canvas::Canvas). Any unsupported construct fails gracefully with a
//! [`MermaidError`](crate::error::MermaidError), which the block renderer turns into a
//! captioned code block.

pub mod ast;
pub mod layout;
pub mod parse;

use crate::canvas::Canvas;
use crate::error::MermaidError;
use crate::theme::Theme;

/// Renders a mermaid source block into a canvas exactly `width` columns wide.
///
/// This is the single entry point the block renderer calls for a ```` ```mermaid ````
/// fence.
///
/// # Errors
///
/// Returns a [`MermaidError`] when the source is malformed or uses a construct outside
/// the supported subset. The caller is expected to fall back to a captioned code block
/// rather than treating this as fatal.
pub fn render_mermaid(src: &str, width: u16, theme: &Theme) -> Result<Canvas, MermaidError> {
    render_diagram(&parse::parse(src)?, width, theme)
}

/// Renders an already-parsed diagram into a canvas exactly `width` columns wide.
///
/// # Errors
///
/// Returns a [`MermaidError`] when the diagram cannot be laid out within `width`.
pub fn render_diagram(
    diagram: &ast::Diagram,
    _width: u16,
    _theme: &Theme,
) -> Result<Canvas, MermaidError> {
    // TODO(dispatch): each arm is wired up as its renderer lands. Owned by the team
    // lead, not by the family agents — do not edit this file.
    let family = match diagram {
        ast::Diagram::Flowchart(_) => "flowchart",
        ast::Diagram::Sequence(_) => "sequenceDiagram",
        ast::Diagram::Class(_) => "classDiagram",
        ast::Diagram::Er(_) => "erDiagram",
        ast::Diagram::State(_) => "stateDiagram",
        ast::Diagram::Pie(_) => "pie",
        ast::Diagram::Gantt(_) => "gantt",
    };
    Err(MermaidError::UnsupportedFamily(family.to_string()))
}
